# Generated by Django 5.2.4 on 2025-07-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Configuration Category',
                'verbose_name_plural': 'Configuration Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Configuration Key')),
                ('display_name', models.CharField(max_length=150, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], max_length=20, verbose_name='Value Type')),
                ('string_value', models.TextField(blank=True, verbose_name='String Value')),
                ('integer_value', models.BigIntegerField(blank=True, null=True, verbose_name='Integer Value')),
                ('float_value', models.FloatField(blank=True, null=True, verbose_name='Float Value')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='Boolean Value')),
                ('json_value', models.JSONField(blank=True, null=True, verbose_name='JSON Value')),
                ('default_value', models.TextField(blank=True, verbose_name='Default Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.configurationcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ['category__order', 'order', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
